import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const roboto = localFont({
  src: [
    {
      path: "./fonts/roboto/RobotoMono-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/roboto/RobotoMono-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/roboto/RobotoMono-Medium.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/roboto/RobotoMono-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/roboto/RobotoMono-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-roboto",
});

const reiswar = localFont({
  src: "./fonts/reiswar/Reiswar.woff2",
  variable: "--font-reiswar",
  weight: "500",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${reiswar.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
